import Head from 'next/head';
import { useState } from 'react';
import ArrowNav from '../components/ArrowNav';
import Separator from '../components/base/Separator';
import Content from '../components/Content';
import MenuBar from '../components/MenuBar';
import Navbar from '../components/Navbar';
import ProfileHeader from '../components/profile-header/ProfileHeader';

export default function Home() {
  const [isMainActive, setIsMainActive] = useState(true);

  return (
    <div>
      <Head>
        <title>Elitely | Get a date easily</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ArrowNav desc="Explore" />
        <ProfileHeader />
        <div className="bg-[#FAFAFA] pb-16 ">
          <Navbar
            setIsMainActive={setIsMainActive}
            isMainActive={isMainActive}
          />
          <Separator />
          <Content isMainActive={isMainActive} />
        </div>
        <MenuBar />
      </main>
    </div>
  );
}
